service: example-serverless-express-app

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: ap-southeast-2

functions:
  thefunction:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}

plugins:
    - serverless-offline
    - serverless-plugin-include-dependencies