service: example-serverless-express-app

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: ap-southeast-2
functions:
  backend:
    handler: dist/lambda.handler
    events:
      - http:
          path: / # this matches the base path
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - dist/**
  exclude:
    - src/**

plugins:
    - serverless-offline
    - serverless-plugin-include-dependencies
    - serverless-api-gateway-throttling

custom:
  # Configures throttling settings for all http endpoints
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 100

