service: example-serverless-express-app

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: ap-southeast-2

functions:
  express:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http:
          path: /
          method: ANY

plugins:
    - serverless-offline
    - serverless-plugin-include-dependencies